default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
      - id: check-toml

  - repo: https://github.com/fpgmaas/deptry.git
    rev: "0.25.1"
    hooks:
      - id: deptry
        args: ["--ignore=DEP001,DEP002"]
