exclude: '^src/exposition/'

default_install_hook_types: [pre-commit, pre-push, commit-msg]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml
- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.8.3
  hooks:
    - id: commitizen
      stages: [commit-msg]
    - id: commitizen-branch
      stages: [pre-push]
- repo: https://github.com/fpgmaas/deptry.git
  rev: "0.23.0"
  hooks:
    - id: deptry
      args: [--ignore, "DEP001,DEP003", --per-rule-ignores, "DEP002=dbt-core|fsspec|dbt-duckdb"]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.1
  hooks:
    - id: ruff # `ruff check`
      args: [ --fix ]
    - id: ruff-format # `ruff format`
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.16.1
  hooks:
    - id: mypy
      verbose: true
      args: [ --install-types, --non-interactive, --pretty, --disallow-untyped-defs, --strict-equality,  --warn-no-return, --ignore-missing-imports, --no-namespace-packages]
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 3.4.1
  hooks:
    - id: sqlfluff-lint # returns linting errors.
      additional_dependencies: ['dbt-core>=1.10.2', 'dbt-duckdb>=1.9.4', 'sqlfluff-templater-dbt>=3.4.1', 'fsspec[s3]>=2025.5.1']
      args: [--config, .sqlfluff, src/transformation/dbt_paris_event_analyzer/]
    - id: sqlfluff-fix # attempts to fix rule violations.
      args: [--config, .sqlfluff, --show-lint-violations,  src/transformation/dbt_paris_event_analyzer/]
      additional_dependencies: ['dbt-core>=1.10.2', 'dbt-duckdb>=1.9.4', 'sqlfluff-templater-dbt>=3.4.1', 'fsspec[s3]>=2025.5.1']
