repos:
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
    -   id: commitizen
        stages:
        - commit-msg
    -   id: commitizen-branch
        stages:
        - pre-push
default_install_hook_types:
- pre-commit
- pre-push
- commit-msg

repos:
- repo: https://github.com/fpgmaas/deptry.git
  rev: "0.23.0"
  hooks:
    - id: deptry
      args: [--ignore, DEP001]