repos:
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
    -   id: commitizen
        stages:
        - commit-msg
    -   id: commitizen-branch
        stages:
        - pre-push
default_install_hook_types:
- pre-commit
- pre-push
- commit-msg
