SELECT
    id,
    event_id,
    "url",
    title,
    lead_text,
    "description",
    date_start,
    date_end,
    coalesce(date_end < current_localtimestamp(), FALSE) AS is_outdated,
    occurrences,
    date_description,
    cover_url,
    cover_credit,
    address_name,
    address_street,
    address_zipcode,
    st_x(lat_lon) AS lon,
    st_y(lat_lon) AS lat,
    NOT coalesce((address_name IS NULL AND address_street IS NULL AND address_zipcode IS NULL), FALSE) AS address_is_indicated,
    pmr,
    blind,
    deaf,
    sign_language,
    mental,
    contact_url,
    contact_phone,
    contact_mail,
    contact_facebook,
    price_type,
    CASE price_detail
        WHEN '<p></p>' THEN NULL
        WHEN '<p></p><p></p>' THEN NULL
        ELSE price_detail
    END AS price_detail,
    access_link,
    access_link_text,
    updated_at,
    programs,
    title_event,
    audience,
    rank,
    qfap_tags,
    contact_organisation_name,
    contact_url_text,
    contact_instagram
FROM {{ ref('raw_events') }}
