
name: check mission 3

on:
  pull_request:
    branches: [ "mission-3-commitizen-deptry" ]


jobs:
  check-mission-3:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest

    env:
      PYTHON: "3.12"

    steps:
      - name: Check out ${{ github.repository }} repository code
        uses: actions/checkout@v4
      - name: Check file existence
        uses: andstor/file-existence-action@v3
        with:
          files: ".pre-commit-config.yaml, pyproject.toml, uv.lock, justfile"
          fail: true
      - name: Check packages installation
        run: (for f in "commitizen" "deptry"; do if grep -qF "$f" pyproject.toml; then echo "✅ $f"; else echo "❌ $f" && exit 1; fi; done;)
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.x"
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
      - name: Installing Python ${{ env.PYTHON }}
        run: uv python install ${{ env.PYTHON }}
      - name: Sync Python dev environment only
        run: uv sync --frozen --dev
      - name: Run the pre-commit hooks via just
        run: uv run just quality-all
      - name: Reveal Secret
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Mais quel génie !

            Commitizen pour la gestion des commits + Deptry pour vérifier nos dépendances, c'est exactement ce qu'il nous fallait !

            Voici ton precieux :gift: : [ouvre moi :file_folder:](${{ vars.INDICE_3 }})
          reactions: hooray
