
name: check mission 4

on:
  pull_request:
    branches: [ "mission-4-ruff-mypy" ]


jobs:
  check-mission-4:
    runs-on: ubuntu-latest

    env:
      PYTHON: "3.12"

    steps:
      - name: Check out ${{ github.repository }} repository code
        uses: actions/checkout@v4
      - name: Check file existence
        uses: andstor/file-existence-action@v3
        with:
          files: "src/logger/__init__.py, src/ingestion/__init__.py, src/logger/log_handler.py"
          fail: true
      - name: Check file absence
        run: |
          [ ! -e "src/paris_events_analyzer.egg-info/" ]
      - name: Check packages installation
        run: (for f in "ruff" "mypy"; do grep -qF "$f" pyproject.toml && echo "✅ $f" || echo "❌ $f"; done; exit 1)
      - name: Check logger implementation
        run: |
          [ $(grep -Fr --include="*.py" "rprint(" . | wc -l) = 0 ]
          [ $(grep -Fr --include="*.py" "log." . | wc -l) = 10 ]
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.x"
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
      - name: Installing Python ${{ env.PYTHON }}
        run: uv python install ${{ env.PYTHON }}
      - name: Sync Python environment
        run: uv sync --frozen
      - name: Run the pre-commit hooks via just
        run: uv run just quality-all
      - name: Reveal Secret
        run: echo "Fourth secret unlocked -> ${{ env.INDICE_4 }}"
