
name: check mission 4

on:
  pull_request:
    branches: [ "mission-4-ruff-mypy" ]


jobs:
  check-mission-4:
    runs-on: ubuntu-latest

    env:
      PRECOMMIT_CI_CONFIG_GIST_ID: "8ea103f7c3bbda18007720df988311c3"
      PRECOMMIT_CI_CONFIG: ".pre-commit-config-4.yaml"
      PYTHON: "3.12"

    steps:
      - name: Check out ${{ github.repository }} repository code
        uses: actions/checkout@v4
      - name: Clone the pre-commit hook associated from Gist
        run: |
          git clone https://gist.github.com/CAprogs/${{ env.PRECOMMIT_CI_CONFIG_GIST_ID }}.git tmp_gist
          mv tmp_gist/* .
          rm -rf tmp_gist
      - name: Check file existence
        uses: andstor/file-existence-action@v3
        with:
          files: "${{ env.PRECOMMIT_CI_CONFIG }}, pyproject.toml, uv.lock, justfile, src/logger/log_handler.py"
          fail: true
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.x"
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
      - name: Installing Python ${{ env.PYTHON }}
        run: uv python install ${{ env.PYTHON }}
      - name: Sync Python dev environment only
        run: uv sync --frozen --dev
      - name: Install the pre-commit hooks
        run: uv run pre-commit install --install-hooks -c ${{ env.PRECOMMIT_CI_CONFIG }}
      - name: Run the pre-commit CI hooks
        run: uv run pre-commit run --all-files -c ${{ env.PRECOMMIT_CI_CONFIG }}
      - name: Reveal Secret
        run: echo "Fourth secret unlocked -> ${{ secrets.INDICE_4 }}"
