
name: check mission 3

on:
  pull_request:
    branches: [ "mission-3-commitizen-deptry" ]


jobs:
  check-mission-3:
    runs-on: ubuntu-latest

    env:
      PYTHON: "3.12"

    steps:
      - name: Check out ${{ github.repository }} repository code
        uses: actions/checkout@v4
      - name: Check file existence
        uses: andstor/file-existence-action@v3
        with:
          files: ".pre-commit-config.yaml, pyproject.toml, uv.lock, justfile"
          fail: true
      - name: Check packages installation
        run: (for f in "commitizen" "deptry"; do grep -qF "$f" pyproject.toml && echo "✅ $f" || echo "❌ $f"; done; exit 1)
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.x"
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
      - name: Installing Python ${{ env.PYTHON }}
        run: uv python install ${{ env.PYTHON }}
      - name: Sync Python dev environment only
        run: uv sync --frozen --dev
      - name: Run the pre-commit hooks via just
        run: uv run just quality-all
      - name: Reveal Secret
        run: echo "Third secret unlocked -> ${{ env.INDICE_3 }}"
